apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: hello-kubernetes
        image: gcr.io/decisive-plasma-333810/backend
        ports:
        - containerPort: 8080
        env:
        - name: DB_SERVER
          value: 34.136.21.112
        - name: POSTGRES_DB
          value: test
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: admin123
